### PR TITLE
Add EGG::Disposer

### PR DESCRIPTION
**Pull request by riidefi**

### CODE REVIEW

**Comment by vabold** [comment]
Any reason for `m_containHeap != nullptr` instead of `m_containHeap`?

**Comment by riidefi** [comment]
> Any reason for `m_containHeap != nullptr` instead of `m_containHeap`?

https://abseil.io/tips/141

**Comment by stblr** [comment]
Do we still want this now that a simpler approach was chosen in #536?

**Comment by riidefi** [comment]
It can't hurt to have this header available moving forward.

**Review by stblr — APPROVED** [review]

**Pull request merged**
