### PR TITLE
Remove the course cache

### PR DESCRIPTION
**Pull request by stblr**
This seems to work but needs more testing as this has the potential to break a lot of things.

### CODE REVIEW

**Comment by nicl83** [comment]
Was asked by @GnomedDev to try a build from this branch after hitting an OoM when trying to change ghost data in a Time Trial. Seems to fix #530 and haven't noticed any major issues, but haven't tried local or online multiplayer yet

**Comment by stblr** [comment]
> Was asked by @GnomedDev to try a build from this branch after hitting an OoM when trying to change ghost data in a Time Trial. Seems to fix #530 and haven't noticed any major issues, but haven't tried local or online multiplayer yet

Thanks for the feedback!

**Comment by stblr** [comment]
For this we still need to think about track identification.

**Comment by GnomedDev** [comment]
What do you mean by that?

**Comment by stblr** [comment]
With the course cache we could easily get a hash of the track to filter ghosts (CTGP and MKW-SP ghosts store that in the ghost file). The simplest way to work around that would be to hash everything on startup but that's way too slow and doesn't handle NetStorage.

**Pull request merged**
